export const CRYPTOS = [
  {
    key: "btc",
    label: "Bitcoin",
    symbol: "BTC",
    network: "Bitcoin",
    icon: "logos:bitcoin",
    scheme: "bitcoin:",
  },
  {
    key: "eth",
    label: "Ethereum",
    symbol: "ETH",
    network: "Ethereum (ERC20)",
    icon: "logos:ethereum",
    scheme: "ethereum:",
  },
  {
    key: "xrp",
    label: "Ripple",
    symbol: "XRP",
    network: "Ripple",
    icon: "cryptocurrency:xrp",
    scheme: "ripple:",
  },
  {
    key: "usdt_trc20",
    label: "USDT_TRC20",
    symbol: "USDT",
    network: "TRC20",
    icon: "cryptocurrency:usdt",
    scheme: "",
  },
  {
    key: "usdt_bep20",
    label: "USDT",
    symbol: "USDT",
    network: "BEP20",
    icon: "cryptocurrency:usdt",
    scheme: "",
  },
  {
    key: "usdt_erc20",
    label: "USDT",
    symbol: "USDT",
    network: "ERC20",
    icon: "cryptocurrency:usdt",
    scheme: "",
  },
];
